export const ROASTS: Record<number, string[]> = {
  0: [
    "This password folds faster than your attention span.",
    "Your password has the structural integrity of a wet paper towel.",
    "Hackers wouldn't crack this, they'd accidentally trip over it.",
    "Your password has the structural integrity of wet cardboard.",
    "This password is basically an open invitation.",
    "You protected your account the way people protect fries from seagulls.",
    "This password is one of your many appalling desicions",
    "You somehow made security sound optional.",
    "You’ve reached a level of vulnerability that’s almost statistically impossible.",
    "Even your keyboard looked disappointed while typing it.",
    "The only thing this password protects is a hacker's self-esteem.",
    "This password has the survival instincts of a pigeon.",
    "Your account is guarded by hopes, dreams, and absolutely nothing else.",
    "This isn’t a password, it’s just proof of your intellectual handicap.",
  ],

  1: [
    "You clearly learned what a capital letter is, but stopped right there.",
    "Congratulations on putting in the bare minimum required to make me sigh.",
    "This password has 'I'll change it later' written all over it (you won't).",
    "It’s cute that you thought this would stop anyone.",
    "A toddler mashing keys might actually come up with something more secure.",
    "This password isn't terrible, which somehow makes it more disappointing.",
    "You almost tried, and that's the tragedy here.",
    "A hacker might need two guesses instead of one.",
    "Your password is acting like it wants attention more than protection.",
    "This feels like your password would apologize to the hacker after getting cracked.",
    "This password has strong participation trophy energy.",
    "You've added just enough effort to avoid embarrassment, but not enough not to be laughed at.",
    "The security equivalent of leaving your doors unlocked at night",
    "Your optimism is doing all the heavy lifting.",
    "This feels like a last-minute school assignment.",
    "A squirrel could probably crack this.",
    "You upgraded from awful to questionable.",
    "This password survived exactly one brainstorming session.",
    "You aimed for secure and landed on convenient.",
    "It's weak, but with extra steps.",
    "This password feels personally offended by complexity.",
    "You clearly know stronger passwords exist and chose violence.",
    "Hackers appreciate customers like you.",
    "This password puts the bare minimum on a pedestal.",
    "Your security strategy appears to be wishful thinking.",
    "This is less ‘secure password’ and more ‘please be nice to me, attacker-san~"
  ],

  2: [
    "You clearly tried, then got distracted halfway through.",
    "This password feels like a group project where nobody showed up.",
    "You put in just enough effort to disappoint everyone equally.",
    "This password radiates good enough energy.",
    "I've seen people spend longer choosing a profile picture.",
    "This password is aggressively average.",
    "Not terrible, not good, just floating through life unnoticed.",
    "This password is held together by optimism.",
    "It looks like effort happened briefly.",
    "This password screams future me will deal with it.",
    "Half lazy, half ambitious, fully confusing.",
    "Mediocrity has rarely been this efficient.",
    "This password could be worse, which isn't much of an achievement.",
    "You clearly know what you're doing, but you're too lazy to actually do it.",
    "This is the security equivalent of hiding your key under the doormat.",
    "It’s aggressively mediocre, much like your general approach to life.",
    "Your security strategy is basically emotional support and vibes."
  ],

  3: [
    "You were so close to greatness and somehow still tripped.",
    "One more push and I'd stop making fun of you.",
    "You've clearly learned from mistakes, just not all of them.",
    "You were cooking, then took the pan off too early.",
    "Not bad, but confidence would be premature.",
    "This password survived the tutorial but not the final boss.",
    "It’s robust enough that I’ll stop roasting you, but don't get cocky.",
    "You’ve managed to be smarter than the average user, which is a very low bar.",
    "So close, yet so far.",
    "My grandam could do better.",
    "I searched for disaster and found mild disappointment.",
    "Secure enough to make hackers sigh, not quit.",
    "You escaped embarrassment by a narrow margin.",
    "Respectable effort, questionable finishing move.",
    "Not bad. It almost makes me believe you might actually know what you're doing."
  ],

  4: [
    "Finally, a password that doesn't make me want to delete your account for you.",
    "I searched for a reason to mock you, but you left me with nothing. How rude.",
    "You’ve managed to be competent. Don't let it become a habit.",
    "This is actually secure. I hate that I have to acknowledge your success.",
    "You’ve set a high bar, which just means you’re going to disappoint me next time.",
    "This password is good. Seriously. Now stop showing off.",
    "Finally, a password that isn't an embarrassment to the keyboard it was typed on.",
    "Did you choose this because you wanted the hacker to feel like they earned it?",
    "This password is actually strong, not that I'm impressed or anything.",
    "Fine, it's good, but don't start acting all mighty.",
    "Annoyingly competent work for once.",
    "You did well, and I hate having to admit that.",
    "Strong password. Try not to let it go to your head.",
    "Against all odds, you made a smart decision.",
    "This password is solid, but you're still an intellectual cripple.",
    "You finally used your brain. The password may be of some use.",
    "Good security? From you? Unexpected.",
    "This password actually deserves respect, regrettably.",
    "Strong enough to make hackers look elsewhere. You sure you came up with it yourself?",
    "You cooked, and now I have fewer insults available.",
    "This password is excellent, which feels deeply unfair.",
    "Congratulations on achieving competence.",
    "I checked for weaknesses and found mostly attitude.",
    "This password is built like a bunker, unfortunately.",
    "Good job. Don't make me repeat that.",
    "Your password is impressive, and I resent you for it"
  ]
};